sub banner {
log |\  __|\___     ==========================================================
log | \/  _  o \                         fishScript v0.1
log | /\  \  ___|   For more info visit https://kettle3d.github.io/fishScript/
log |/  \______/    ==========================================================
}

sub fish {
log |\  __|\___
log | \/  _  o \
log | /\  \  ___|
log |/  \______/
}
sub oof {
log | \     _ _ | \ _ _ _           = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
log 
log |   \ /     _     o   \         f i s h S c r i p t   C o m p i l e r   v 0 . 1 
log 
log |   / \     \     _ _ _ |       F o r   m o r e   i n f o   v i s i t   h t t p s : / / k e t t l e 3 d . g i t h u b . i o / f i s h S c r i p t / 
log 
log | /     \ _ _ _ _ _ _ /         = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
}